;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((gfm-mode . ((flycheck-checker . markdown-markdownlint-cli)))
 (sh-mode . ((shfmt-arguments . "-i 4 -p -ci")
             (shfmt-executable . /home/swarnendu/software/shfmt_v3\.0)
             (flycheck-checker . sh-shellcheck)))
 (python-mode . ((flycheck-pylintrc . "setup.cfg")
                 (python-check-command . "pylint")
                 (lsp-pyls-plugins-yapf-enabled . t)
                 (flycheck-python-pylint-executable . "python3")
                 (lsp-pyls-plugins-pylint-args . "-j 2")
                 (lsp-pyls-plugins-pylint-enabled . t)
                 (flycheck-checker . python-pylint)
                 (lsp-python-ms-extra-paths . ["/home/swarnendu/prospar-workspace/data-race-framework/src"]))))
