* Interesting quotes

"Show me your ~/.emacs~, and I will tell you who you are." -- Bogdan Maryniuk.

"People talk about getting used to a new editor, but over time, it is precisely the opposite that should happen - the editor should get used to us." -- Vivek Haldar in "New frontiers in text editing."

"Emacs is like a laser-guided missile. It only has to be slightly misconfigured to ruin your whole day." -- Sean McGrath.

"While any text editor can save your files, only Emacs can save your soul." -- Per Abrahamsen.

"In the GNU/Linux world, there are two major text editing programs: the minimalist vi (known in some implementations as elvis) and the maximalist Emacs. I use Emacs, which might be thought of as a thermonuclear word processor. It was created by Richard Stallman; enough said. It is written in Lisp, which is the only computer language that is beautiful. It is colossal, and yet it only edits straight ASCII text files, which is to say, no fonts, no boldface, no underlining. In other words, the engineer-hours that, in the case of Microsoft Word, were devoted to features like mail merge, and the ability to embed feature-length motion pictures in corporate memoranda, were, in the case of emacs, focused with maniacal intensity on the deceptively simple-seeming problem of editing text. If you are a professional writer - i.e., if someone else is getting paid to worry about how your words are formatted and printed - emacs outshines all other editing software in approximately the same way that the noonday sun does the stars. It is not just bigger and brighter; it simply makes everything else vanish." - Neal Stephenson, In the Beginning was the Command Line (1998), http://www.cryptonomicon.com/beginning.html.

"Nearly everybody is convinced that every style but their own is ugly and unreadable. Leave out the "but their own" and they are probably right..." -- Jerry Coffin (on indentation).

"The only real difficulties in programming are cache invalidation and naming things." -- Phil Karlton.

"Good code is its own best documentation. As you're about to add a comment, ask yourself, "How can I improve the code so that this comment isn't needed?" Improve the code and then document it to make it even clearer." -- Steve McConnell.

"What I don't understand is: why should you ever care how your editor looks unless you're trying to win a screenshot competition? The primary factor in looking good should be the choice of a good font at a comfortable size and a syntax coloring theme that you like. And that is not something specific to an editor. Editors like Emacs and vi have almost no UI! If Emacs is configured right, the only UI it has is the modeline and the minibuffer." -- Vivek Haldar in "New frontiers in text editing."

"Good code is like a good joke - it needs no explanation." -- Russ Olsen.

"As a poke at Emacs' creeping featurism, vi advocates have been known to describe Emacs as "a great operating system, lacking only a decent editor"." -- Editor war (https://en.wikipedia.org/wiki/Editor_war).

"Emacs was a really great idea in the seventies, and one of the frightening things about Emacs today is if you skip the last 20 years, it is much the same." -- Don't use Emacs, says Java's father (http://www.computerworld.com.au/article/207799/don_t_use_emacs_says_java_father/).

"Bad programming is easy. Even Dummies can learn it in 21 days." -- Felleisen et al. in "How to Design Programs".

"A language that doesn't affect the way you think about programming is not worth knowing." -- Alan Perlis.

"I swear you spend just as much time configuring Emacs as you do coding other stuff."

"Emacs saves you time when you work, and takes it back when you play with it" -- http://puntoblogspot.blogspot.com/

"Emacs isn't an editor. It's an interpreter that happens to ship with an editor program. It makes a lot more sense with this mindset." -- Wilfred Hughes.

"Lisp isn't a language; it's a building material." -Alan Kay.

"The reasonable man adapts himself to Emacs; the unreasonable one persists in trying to adapt Emacs to himself. Therefore all progress depends on the unreasonable man." - Adapted from G. B. Shaw's quote.

"Compared to Emacs Wizards, graphical-IDE users are the equivalent of amateur musicians, pawing at their instrument with a sort of desperation. An IDE has blinking lights and pretty dialogs that you can't interact with properly and gives newbies a nice comfortable sense of control. But that control is extremely crude and all serious programmers prefer something that gives them more power." -Steve Yegge.

"Emacs is to man what maternity is to a woman. From a philosophical and doctrinal viewpoint, I do not believe in perpetual peace."

"Give me six hours to finish a task, and I will spend the first four making sure I have tweaked my Emacs config to handle the task."

"There are no bad Emacs configurations, only poor applications of them."
